### ISSUE TITLE
Folium module is not and cannot be installed

### ISSUE THREAD

**Issue by lefterav** [MobilityNet/mobilitynet.github.io#6]
Hi I started following the quickstart tutorial. I created a local virtualenv, then run Jupyter on it and opened this notebook: 

https://github.com/MobilityNet/mobilitynet-analysis-scripts/blob/master/spec_creation/Validate_spec_before_upload.ipynb

Then on the second step I get this message:
```
ImportError                               Traceback (most recent call last)
<ipython-input-2-c63b4c1db4dd> in <module>()
----> 1 import folium
      2 import folium.features as fof
      3 import folium.utilities as ful
      4 import branca.element as bre
      5 import json
```

ImportError: No module named folium

I tried to install folium from the commandline within virtualenv, but it gives this error:

```
ERROR: Command errored out with exit status 1:
     command: /home/lefterav/sandbox/mobilitynet/mobilitynet/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hHYift/branca/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hHYift/branca/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hHYift/branca/pip-egg-info
         cwd: /tmp/pip-install-hHYift/branca/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hHYift/branca/setup.py", line 41
        print(error, file=sys.stderr)  # noqa
                         ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by maufadel** [comment]
Hi Eleftherios, I've installed the environment using `conda env create -f  setup/environment.yml`, activated it and started Jupiter notebook from that same terminal. folium is present in the environment so I managed to run the notebook without any problem. One file is not found because its path is incorrect, but I've fixed that, I'll commit my code to fix that.

**Comment by lefterav** [comment]
Then maybe we should instruct users at the quickstart to use miniconda. Cause most tutorials out there suggest using virtualenv, which is what I followed.
